blank_issues_enabled: false
contact_links:
  - name: Awesome Jev Discussions & Ideas
    url: https://github.com/bakiabaci/awesome-jev/discussions
    about: Ask questions or discuss new System One & Jev architectural ideas.
